In [9]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Adam'],
    'last': ['Schafer', 'Doe', 'Doe', 'Doe'],
    'email': ['CoreyMSchafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com', 'A@email.com']
}

# a new name was added: Adam Doe with email A@email.com

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame(people)

In [12]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe              A@email.com

In [13]:
df.sort_values(by='last')

   first     last                    email
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe              A@email.com
0  Corey  Schafer  CoreyMSchafer@email.com

In [14]:
df.sort_values(by='last', ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe              A@email.com

In [16]:
# for example, if we wanted to sort by last name and then first name, we could do the following:
df.sort_values(by=['last', 'first'], ascending=False)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
2   John      Doe        JohnDoe@email.com
1   Jane      Doe        JaneDoe@email.com
3   Adam      Doe              A@email.com

In [18]:
df.sort_values(by=['last', 'first'], ascending=[False,True], inplace=True)
# this sorts the DataFrame by last name in descending order, and then by first name in ascending order

df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
3   Adam      Doe              A@email.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [19]:
df.sort_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   Adam      Doe              A@email.com

In [21]:
df['last'].sort_values()
# this will show us a sorted Series of the last names

3        Doe
1        Doe
2        Doe
0    Schafer
Name: last, dtype: str