In [1]:
people = {
    'first': ['Corey', 'Jane', 'John'],
    'last': ['Schafer', 'Doe', 'Doe'],
    'email': ['CoreyMSchafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@email.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

- Adding columns

In [ ]:
df['first'] + ' ' + df['last']
# we're getting a Series with the first and last names concatenated with a space between them.

0    Corey Schafer
1         Jane Doe
2         John Doe
dtype: str

In [6]:
# we're creating a new column and assigning it the concatenated first and last names
df['full_name'] = df['first'] + ' ' + df['last']  # creating the new column with concatenated names
df  # displaying the updated DataFrame

   first     last                    email      full_name
0  Corey  Schafer  CoreyMSchafer@email.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

- Removing columns

In [ ]:
df.drop(columns=['first', 'last'], inplace=True) # removing the 'first' and 'last' columns from the DataFrame
df  # displaying the updated DataFrame

                     email      full_name
0  CoreyMSchafer@email.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [10]:
# now doing the reverse: spliting the full name into first and last names
df['full_name'].str.split(' ', expand=True)  # splitting the 'full_name' column into two separate columns

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [11]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)
df  # displaying the updated DataFrame with the split first and last names

                     email      full_name  first     last
0  CoreyMSchafer@email.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

- Adding and Removing rows of Data

In [19]:
# adding a single row of data
#df.append({'first': 'Tony'}, ignore_index=True)

df.loc[len(df)] = {'first': 'Tony'} 
# Note: the append method was removed in newer versions of pandas, so I use loc instead
df

                     email      full_name  first     last
0  CoreyMSchafer@email.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [20]:
people2 = {
    'first': ['Tony', 'Steve'],
    'last': ['Stark', 'Rogers'],
    'email': ['IronMan@avenge.com', 'Cap@avenge.com']
}

df2 = pd.DataFrame(people2)  # creating a DataFrame from the people2 dictionary

In [21]:
df2

   first    last               email
0   Tony   Stark  IronMan@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [22]:
# adding a dataframe into another dataframe
df = pd.concat([df, df2], ignore_index=True)  # combining the two DataFrames
df  # displaying the updated DataFrame

                     email      full_name  first     last
0  CoreyMSchafer@email.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers

In [23]:
# removing rows
df.drop(index=5)

                     email      full_name  first     last
0  CoreyMSchafer@email.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark

In [25]:
# now we're removing rows based on a condition. In this case, we're removing rows where the 'last' name is 'Doe'.
filt = df['last'] == 'Doe'  # creating a filter for rows where the 'last' name is 'Doe'

df.drop(index=df[filt].index)

                     email      full_name  first     last
0  CoreyMSchafer@email.com  Corey Schafer  Corey  Schafer
3                      NaN            NaN   Tony      NaN
4       IronMan@avenge.com            NaN   Tony    Stark
5           Cap@avenge.com            NaN  Steve   Rogers