-- Creating a simple dataframe with a python dictionary

In [12]:
people = {
    "first" : ["Corey", "Jane", "John"],
    "last" : ["Schafer", "Doe", "Doe"],
    "email" : ["CoreyMSchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"]
}

In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame(people)

In [15]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [16]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@gmail.com
2          JohnDoe@gmail.com
Name: email, dtype: str

In [17]:
df.set_index('email')
# by doing this, we are turning the email values into the indexes of the DataFrame.

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@gmail.com         Jane      Doe
JohnDoe@gmail.com         John      Doe

In [18]:
df
# the dataframe is still the same, because pandas doesn't do a lot of these kind of changes inplace unless we explicitly tell it to do so

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [19]:
df.set_index('email', inplace=True)

In [20]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@gmail.com         Jane      Doe
JohnDoe@gmail.com         John      Doe

In [21]:
df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@gmail.com', 'JohnDoe@gmail.com'], dtype='str', name='email')

In [26]:
df.loc['CoreyMSchafer@gmail.com']
# now we can search rows by their index labels instead of their row numbers!

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [25]:
df.loc['CoreyMSchafer@gmail.com', 'last']

'Schafer'

In [29]:
df.iloc[0]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [ ]:
df.reset_index(inplace=True)
df
# we can reset the index back to the default integer index!

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@gmail.com   Jane      Doe
2        JohnDoe@gmail.com   John      Doe