In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [12]:
filt = (df['last'] == 'Doe')

In [14]:
df[filt]

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [15]:
df.loc[filt]

  first last              email
1  Jane  Doe  JaneDoe@gmail.com
2  John  Doe  JohnDoe@gmail.com

In [16]:
df.loc[filt, 'email']

1    JaneDoe@gmail.com
2    JohnDoe@gmail.com
Name: email, dtype: str

In [17]:
filt_2 = (df['last'] == 'Doe') & (df['first'] == 'John')

In [18]:
df.loc[filt_2, 'email']

2    JohnDoe@gmail.com
Name: email, dtype: str

In [19]:
filt_3 = (df['last'] == 'Schafer') | (df['first'] == 'John')

In [21]:
df.loc[filt_3, 'email']

0    CoreyMSchafer@gmail.com
2          JohnDoe@gmail.com
Name: email, dtype: str

In [24]:
df.loc[~filt_3, 'email']
# the simbol ~ means NOT, so this will return all the emails that are NOT in the filter filt_3

1    JaneDoe@gmail.com
Name: email, dtype: str