In [2]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", "Doe", "Doe"],
    "email": ["CoreyMSchafer@gmail.com", "JaneDoe@gmail.com", "JohnDoe@gmail.com"]
}

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [7]:
df.columns = ['first_name', 'last_name', 'email']

In [10]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [11]:
df.columns = [x.upper() for x in df.columns]
# this is a list comprehension that loops through each column name and applies the upper() method to it
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [12]:
df.columns = df.columns.str.replace(' ', '_')
# replace any spaces with underscores in the column names
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [14]:
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@gmail.com
2       John       Doe        JohnDoe@gmail.com

In [ ]:
df.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)
# this will rename only the columns specified in the dictionary, and leave the rest of the columns unchanged
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [22]:
df.loc[2] = ['John', 'Smith', 'JohnSmith@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John    Smith      JohnSmith@email.com

In [25]:
df.loc[2, ['last', 'email']] = ['Doe', 'JohnDoe@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [26]:
df.loc[2, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John    Smith        JohnDoe@email.com

In [27]:
df.at[2, 'last'] = 'Doe'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [31]:
# common mistakes when people try to change a single value without indexers
filt = (df['email'] == 'JohnDoe@email.com')
df[filt]['last'] = 'Smith'  # this will not work, it will give a SettingWithCopyWarning

/tmp/ipykernel_6218/936977475.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last'] = 'Smith'  # this will not work, it will give a SettingWithCopyWarning

In [32]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@email.com

In [34]:
# common mistakes when people try to change a single value without indexers
filt = (df['email'] == 'JohnDoe@email.com')
df.loc[filt, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John    Smith        JohnDoe@email.com

-- Examples of how to update multiple rows of data

In [37]:
df['email'] = df['email'].str.lower()
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@gmail.com
2   John    Smith        johndoe@email.com